name: Check Pull Request
on: pull_request

jobs:
  parse_branch_name:
    runs-on: self-hosted

    steps:
      - name: Check if PR target branch is ok
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "pr branch name: $branch_name"
          
          target_branch=${GITHUB_BASE_REF}
          echo "target branch: $target_branch"
          dev_regex="^(fix|feat|refactor|style)/.*$"
          
          if [[ "$branch_name" =~ $dev_regex ]]; then
            echo "Branch name matches with regex pattern."
          else
            echo "Branch name does not match with regex."
            exit 1
          fi
        shell: bash
      - name: Test PR title for conventional commit format
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestTitle = context.payload.pull_request.title;
            console.log(`Pull request title: ${pullRequestTitle}`);
            const pattern = /^(feat|fix|refactor|style): .{1,50}/;
            
            if (pullRequestTitle.match(pattern)) {
                console.log("Title matches conventional commit. Good job");
            } else {
                var message = '@${{ github.event.pull_request.user.login }} Pull request title does not match conventional commit format. Please edit the PR title and the pipeline will run again.';
                github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: message
                })
                core.setFailed(message)
            }